[package]
name = "k"
version = "0.22.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
description = "k is for kinematics"
license = "Apache-2.0"
keywords = ["kinematics", "robotics", "ik"]
categories = ["algorithms"]
repository = "https://github.com/openrr/k"
documentation = "http://docs.rs/k"
readme = "README.md"
edition = "2018"

[features]
default = []
serde-serialize = ["nalgebra/serde-serialize", "serde"]

# Note: nalgebra, simba, urdf-rs, and serde are public dependencies.
[dependencies]
log = "0.4"
nalgebra = "0.25"
simba = "0.3"
thiserror = "1.0"
urdf-rs = "0.6"

serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
doc-comment = "0.3"
kiss3d = "0.29"
rand = "0.8"

#[profile.release]
#debug = true

#[profile.bench]
#debug = true
